spring:
  application:
    name: toy-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: ms1
            uri: http://localhost:8081
            predicates:
              - Path=/ms1/**

          - id: ms2
            uri: http://localhost:8082
            predicates:
              - Path=/ms2/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin1234@localhost:8761/eureka

server:
  port: 8080